name: Generate and Deploy Diagrams

on:
  push:
    branches: [main]
    paths: ['src/**/*.drawio']
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the already running and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Export drawio files to PNG
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: src/
          remove-page-suffix: true
          output: public/
          format: png
          
      - name: Generate simple index page
        run: |
          mkdir -p public
          cat > public/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Incognia Diagrams</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  .diagram { margin: 20px 0; padding: 15px; border: 1px solid #ddd; }
                  img { max-width: 500px; height: auto; }
                  .url { background: #f0f0f0; padding: 5px; font-family: monospace; }
              </style>
          </head>
          <body>
              <h1>📊 Incognia Diagrams</h1>
              <p>URL base: <code>https://incogniadev.github.io/Diagrams/</code></p>
          EOF
          
          # Add diagrams to index
          find public -name "*.png" 2>/dev/null | while read img; do
            if [ -f "$img" ]; then
              rel_path=${img#public/}
              name=$(basename "$img" .png)
              echo "<div class='diagram'>" >> public/index.html
              echo "<h3>$name</h3>" >> public/index.html
              echo "<img src='./$rel_path' alt='$name'/>" >> public/index.html
              echo "<div class='url'>https://incogniadev.github.io/Diagrams/$rel_path</div>" >> public/index.html
              echo "</div>" >> public/index.html
            fi
          done
          
          echo "</body></html>" >> public/index.html
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
